### PR TITLE
Change tables to `pipeline_740`

### PR DESCRIPTION
**Pull request by bitsofbits**
* Change tables to reference `pipeline_740`

* Run update scripts to update tables

### CODE REVIEW

**Comment by bitsofbits** [comment]
@pwoods25443 : I was looking at the large number of added vessels in 2016 spoofing and I realized that the 2016 dates only go through August, because they are hard coded 😦 . I propose that, after this PR, I parameterize the dates as well, so it's obvious that they need to be updated for a new release.

**Comment by pwoods25443** [comment]
@bitsofbits I found the problem with 2016.  There were some days that did not get loaded into bigquery, so many of the segments had weird gaps that confused the segment detection query.   I re-loaded everything so we should be good to go now if you just re-generate the output files.

**Comment by bitsofbits** [comment]
@pwoods25443 : I re-generated the output files. Now there are ~1600 changes rather than ~4000. Still a lot, but many fewer. If you're happy with that I'll merge it tomorrow.

**Comment by pwoods25443** [comment]
@bitsofbits everything looks good.  But I see more than ~1600 in the updated 2016 spoofing file

```console
env) Abelard:treniformis paul$ wc -l treniformis/_assets/GFW/SPOOFING_MMSI/2016.txt
    4302 treniformis/_assets/GFW/SPOOFING_MMSI/2016.txt
(env) Abelard:treniformis paul$ 

```

**Comment by bitsofbits** [comment]
@pwoods25443 : I garbled what I was saying, there are bout 1600 changes between the newly generated file and the original file:
```
git diff --stat master update-tables -- treniformis/_assets/GFW/SPOOFING_MMSI/2016.txt 
 treniformis/_assets/GFW/SPOOFING_MMSI/2016.txt | 1577 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------
 1 file changed, 853 insertions(+), 724 deletions(-)
```

**Pull request merged**
