### PR TITLE
Migrate from SkyTruth/vessel-lists

### PR DESCRIPTION
**Pull request by geowurster**
Closes https://github.com/GlobalFishingWatch/treniformis/issues/10
Closes https://github.com/GlobalFishingWatch/treniformis/issues/12

This PR started as https://github.com/GlobalFishingWatch/treniformis/pull/1, but the git history there contains a bunch of files we don't want, so I manually copied everything to this branch.

* Renamed to `treniformis`
* Trashed a bunch of stuff that doesn't belong in the repo
* MVP API

@bitsofbits Ready for final review.

### CODE REVIEW

**Comment by bitsofbits** [comment]
@geowurster, WKV is still around, weren't we going get rid of that?

Also, rather than recopying the branch, to get a clean history, can't we just do a squash commit (https://github.com/blog/2141-squash-your-commits) from the branch to get a clean history?

**Comment by bitsofbits** [comment]
@geowurster, other than the above things look fine.

My OCD is telling me that we may want to tweak the names again because all of these are MMSI lists, yet only one of the paths uses _MMSI in the designation. The top-level names might be better as ("ACTIVE_MMSI", "FISHING_MMSI", "SPOOFING_MMSI") or even ("MMSI/ACTIVE", "MMSI/FISHING", "MMSI/SPOOFING").  I'd be fine renaming things after the merge so we can think about the structure a bit more first.

**Comment by geowurster** [comment]
@bitsofbits Both good points.  I had forgotten about the squash.  You're probably right about the MMSI tag.  I think `ACTIVE_MMSI` is probably better than `MMSI/ACTIVE`.  Not sure how `WKV` made its way back in, but it should be removed.

**Comment by bitsofbits** [comment]
@geowurster, I removed WKV and renamed XXX to XXX_MMSI everywhere. I also fixed the resulting breakage of the `build_combined_fishing_list` and the unit tests.

I think it's good to go. Take a look over the branch when you're back online and if it looks good, please merge it.

**Pull request merged**
